
#ifndef USE_OPENGL

// Color mapping
int COLOR_RGB = 0;
int COLOR_RGBA = 0;
int COLOR_RGB16F = 0;
int COLOR_RED = 0;
int COLOR_RED16F = 0;
int COLOR_RED32F = 0;
int COLOR_DEPTH_COMPONENT32F = 0;
int COLOR_DEPTH_COMPONENT24 = 0;
int COLOR_DEPTH_COMPONENT = 0;

int TEST_EQUAL = 0;
int TEST_LEQUAL = 0;
int TEST_GEQUAL = 0;
int TEST_LESS = 0;
int TEST_GREATER = 0;

int TEXTURE_FILTER_NEAREST = 0;
int TEXTURE_FILTER_LINEAR = 0;
int TEXTURE_FILTER_MIPMAP_LINEAR = 0;

int TEXTURE_FILTER_MINIFICATION = 0;
int TEXTURE_FILTER_MAGNIFICATION = 0;

int COLOR_BUFFER_BIT = 0;
int DEPTH_BUFFER_BIT = 0;
int STENCIL_BUFFER_BIT = 0;

int DRAW_TRIANGLES = 0;
int DRAW_TRIANGLE_STRIP = 0;
int DRAW_PATCHES = 0;

int POLYMODE_FILL = 0;
int POLYMODE_LINE = 0;

int DRAW_BUFFER_NONE = 0;
int DRAW_BUFFER_FRONT = 0;
int DRAW_BUFFER_BACK = 0;

int TEXTURE_WRAP_NONE = 0;
int TEXTURE_WRAP_REPEAT = 0;

int BLEND_ZERO = 0;
int BLEND_ONE = 0;
int BLEND_SRC_COLOR = 0;
int BLEND_ONE_MINUS_SRC_COLOR = 0;
int BLEND_SRC_ALPHA = 0;
int BLEND_ONE_MINUS_SRC_ALPHA = 0;
int BLEND_DST_ALPHA = 0;
int BLEND_ONE_MINUS_DST_ALPHA = 0;

int TEXTURE_SLOT_POSITIVE_X = 0;
int TEXTURE_SLOT_NEGATIVE_X = 0;
int TEXTURE_SLOT_POSITIVE_Y = 0;
int TEXTURE_SLOT_NEGATIVE_Y = 0;
int TEXTURE_SLOT_POSITIVE_Z = 0;
int TEXTURE_SLOT_NEGATIVE_Z = 0;

#endif